dist: trusty
language: node_js
cache: yarn
before_install:
  - sudo add-apt-repository ppa:ethereum/ethereum -y
  - sudo apt-get update
  - sudo apt-get install solc=0.4.24
node_js:
  - '9'
  - '10'
install:
  - yarn install
script:
  - yarn build
  - yarn test
  - yarn lint